# Custom Language File for Launcher Customizer

[ejs.app]
title = "이클립스"

[ejs.landing]
mediaGitHubURL = "https://cafe.naver.com/jiandgarden"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/Eclipse"
supportLink = "https://github.com/CustomLauncherLab/Eclipse/issues"

[ejs.welcome]
welcomeHeader = "이클립스"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
